### ISSUE TITLE
Yandex.Collections share button

### ISSUE THREAD

**Issue by jakwuh** [ilyabirman/Likely#111]
Hi!

First of all, big thanks to all of the contributors for making nice and easy to use social buttons.

It is half a year since [Yandex.Collections](https://c.ya.ru) has launched and now it offers some great options for content discovering, bookmarking and sharing.

I've failed trying to find any contribution docs so I'd like to know if it is ok to prepare a PR for adding the social button?

**Comment by vitkarpov** [comment]
@iamakulov Hey, what do you think? Seems we need design of a new button, don't we?

**Comment by iamakulov** [comment]
Pinging @ilyabirman for the opinion on the button.

Also, I've just enabled the email notifications, so I won't miss the future issues and PRs :D @vitkarpov, thanks for pinging!

**Comment by iamakulov** [comment]
Discussed this. @jakwuh, I'm sorry, I think we won't be adding this button for now, but we may return to this in the future. Anyway, your question is important: we see that there're people that need a specific button, and we start considering it &ndash; so thank you for the interest!

> I've failed trying to find any contribution docs

Yeah, it's a major problem: I don't get enough time to write the docs, and it's probably also unnecessary at the moment because I plan a major refactoring in the near future. We'll get to this sooner or later (we even have #17 for this 😅).

**Comment by jakwuh** [comment]
@iamakulov thank you for your response. Though this issue is closed, please, let me know if you open somehow in a future releases the possibility to opt-in social buttons (perhaps not such popular worldwide but still important to some audience).

**Comment by iamakulov** [comment]
Okay! Can't promise because I can forget it, but if I remember I'll surely notify you.
