### ISSUE TITLE
Ability to replace icon with custom svg

### ISSUE THREAD

**Issue by mrnix** [ilyabirman/Likely#50]
Something about
```html
<div class="likely">
    <div class="facebook">
        <svg class="likely__icon_facebook"><custom-facebook-icon /></svg>
        Share
    </div>
</div>
```

**Comment by iamakulov** [comment]
Could you please explain the example? Do you mean that, when a user provides an `svg` icon in `.facebook`, we should use it instead of the current one?

What pros or cons does this solution have compared to specifying the icon with `data-icon="[svg path]"`? The `data-icon` solution seems less breakable to me, however it fills the markup with the long `data` attributes which is kinda weird.
All current icons are implemented [with a single path](https://github.com/ilyabirman/Likely/blob/master/source/svg.js), by the way.

Also, is there a need to expand this issue and allow replacing the icon not only with `svg` icons, but with `png`, `gif` and other ones?

**Comment by mrnix** [comment]
> use it instead of the current one
Yes, exactly.

>  specifying the icon with `data-icon="[svg path]"` 
It may not give an ability to specify some complex icon, with more than one `path` or set custom png/gif icons.

**Comment by vitkarpov** [comment]
@iamakulov Do we need to implement this?

**Comment by runnickrun** [comment]
I double this. 

Also if we look at the icons itself, Facebook is kinda off because of its logo background. I think Tinkoff journal has a better implementation: 
![2016-09-27 16 30 10](https://cloud.githubusercontent.com/assets/18515722/18876023/c3733df8-84d0-11e6-8571-6d6b3e498f60.png)

Now to change the svg you need to modify js files and gulp them, so it's not easy.

As for additional file types I think it's not needed as plugin concentrates only on social networks, and these are available in svg. Set in HTML though, it won't matter if you're using svg, png, etc.

**Comment by vitkarpov** [comment]
Hm, I don't understand the real problem, which is behind. Why does Tinkoff need a custom facebook logo? I mean, obviously there's a reason to do that, so maybe we should consider it too?

**Comment by iamakulov** [comment]
I discussed this with @ilyabirman, and this won’t be implemented, sorry. We want Likely to be recognizable, and replacing icons decreases our recognizability.

**Comment by iamakulov** [comment]
Sorry, my bad: appears I’ve misunderstood @ilyabirman. Reopening this back, we’ll discuss this again.

**Comment by iamakulov** [comment]
So, well, we’ve got a conclusion. We don’t want to provide tools for changing the icons because we like to keep Likely recognizable _in the default configuration_. However, we don’t want to anyhow avoid changing them _externally_.

As one of the solutions, you can replace an icon using CSS, just like Tinkoff Journal does. Hide the button’s original icon and display your own one instead:

```css
.likely__icon_facebook svg {
    display: none;
}

.likely__icon_facebook {
    background-image: url("your-custom-icon-url");
}
```

Please let us know if you experience problems when changing an icon, we’ll think how to remove the obstacles.

I’m closing this, but feel free to write back if you have a question or anything.
