### ISSUE TITLE
Likely counters don’t always work properly when the buttons are added dynamically

### ISSUE THREAD

**Issue by iamakulov** [ilyabirman/Likely#81]
> Смотри, у нас есть страница подборки со статьями: http://journal.tinkoff.ru/selected/fraud/
Первая статья грузится вместе со страницей с сервера. Разметка остальных записывается в &lt;script type="text/plain">, чтобы не грузилось сразу много картинок, при прокрутке страницы  контент вставляется через innerHTML и парсится. После выполнения innerHTML вызывается likely.initiate() для этой статьи. Для каждого блока .likely в подборке прописан корректный url и title.
Так вот: при лайкли добавляется, статьи можно шарить, но счетчики шаров появляются через раз: в одной статье есть, в другой — нет. Более того, после добавления новой статьи шары могут исчезнуть для старой.

> Если что, инициализация вот так происходит: `likely.initiate(article.querySelector('.likely'));`
article — нода, куда вставляется контент, но сама она подгружается еще со страницей.

This problem is fairly major because Tinkoff Journal is our major user, and the issue is important for them.

**Comment by vitkarpov** [comment]
@iamakulov 

> likely.initiate(article.querySelector('.likely'))

Actually, this doesn't make sense. `likely.initiate` initiates *all buttons on the page*, and accepts options, not a link to node.

Instead of, seems `likely(article.querySelector('.likely'))` is the proper way, assuming `article.querySelector('.likely')` returns single node inside a new article, exactly the node where likely should be initialized.

However, the code `likely.initiate()` actually finds all new widgets, and updates an old ones. So apparently there's a problem with updating existing widget.

I'll try to find the latter out, and Tinkoff's guys can change `likely.initiate` to just `likely(node)`, `cause it's the right way anyway.

**Comment by iamakulov** [comment]
I’ve asked folks to replace `likely.initate(node)` with `likely.initiate()`, this didn’t help. So yep, looks like an issue in our code.

> I'll try to find the latter out, and Tinkoff's guys can change `likely.initiate` to just `likely(node)`, `cause it's the right way anyway. 

Good option, will suggest. Thank you!

**Comment by vitkarpov** [comment]
> likely.initate(node) with likely.initiate()

yep, as this didn't change anything we have a bug with updating existing widgets

**Comment by vitkarpov** [comment]
Reproduced the following case:

- load the test page
- perform `likely.initiate()` in console
- counters have been missed

I think this should be separated into its issue

**Comment by vitkarpov** [comment]
https://github.com/ilyabirman/Likely/issues/83

**Comment by vitkarpov** [comment]
@iamakulov after #83 I believe fellows can perform likely.initiate, as they already do: the new widgets should be initialized and the old ones to be not broken.

**Comment by iamakulov** [comment]
Wow, the reproduced case seems to be related to #75, I’ve seen something similar there. Probably it’s even a single bug.

**Comment by iamakulov** [comment]
Closed in #84.
