### ISSUE TITLE
Get back Twitter count

### ISSUE THREAD

**Issue by runnickrun** [ilyabirman/Likely#96]
This site seems to count Twitter shares: [http://newsharecounts.com](http://newsharecounts.com)
You need to register and add your site to start counting and it won't count previous shares but still seems to work, especially for new sites. 
You can also use their API instead of Twitter's to get counts. 

Any chance adding this?

**Comment by iamakulov** [comment]
Sorry, but we’d rather not. We don’t want to rely on unofficial external services because they can break Likely or cause security problems.

However, if you need it, you can hack around and implement it yourself. Just edit `likely.js` and add these two lines into the Twitter config:

```js
  counterUrl: 'https://public.newsharecounts.com/count.json?url={url}&callback=?', 
  convertNumber: function (counter) { 
    return counter.count; 
  },
```

You can find the config in the file by searching for `twitter.com`. The object that has something like

```js
  popupUrl: 'https://twitter.com/...'
```

is the one you need.

If you use Likely as a CommonJS module, then the things are more complicated. You can edit `likely-commonjs.js`, but it’ll be replaced on an update or re-installation. I don’t have a clear solution for this just yet.

I’m closing this as “Won’t fix” for now, but feel free to write back if you have a suggestion or a question.
